# Generated by Django 4.2.5 on 2023-09-08 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utilisateurs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_naissance', models.DateField(null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.FileField(blank=True, upload_to=utilisateurs.models.renommer_image)),
                ('sexe', models.CharField(choices=[('Non sexe', 'Selectionner sexe'), ('F', 'feminnin'), ('M', 'masculin')], default='Non sexe', max_length=8)),
                ('type_user', models.CharField(choices=[('appre', 'Apprenant(e)'), ('ETU', 'Etudiant(e)'), ('ENSEI', 'Enseignant(e)')], default='ETU', max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
