# Generated by Django 4.2.5 on 2023-09-12 23:33

from django.db import migrations, models
import utilisateurs.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, upload_to=utilisateurs.models.renommer_image),
        ),
        migrations.AlterField(
            model_name='profil',
            name='type_user',
            field=models.CharField(choices=[('Apprenant(e)', 'Apprenant(e)'), ('Etudiant(e)', 'Etudiant(e)'), ('Enseignant(e)', 'Enseignant(e)')], default='Etudiant(e)', max_length=14),
        ),
    ]
