# Generated by Django 4.2.5 on 2023-09-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pdf',
            field=models.ImageField(blank=True, null=True, upload_to='PDF', verbose_name='pdf de cours'),
        ),
    ]
