# Generated by Django 4.2.5 on 2023-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_alter_lesson_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='PDF', verbose_name='pdf de cours'),
        ),
    ]
