# Generated by Django 4.2.5 on 2023-09-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_alter_lesson_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='mime_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
