# Generated by Django 4.2.5 on 2023-09-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_lesson_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
