# Generated by Django 4.2.5 on 2023-09-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_lesson_pdf_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='pdf_content',
        ),
    ]
