# Generated by Django 4.2.5 on 2023-09-28 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0009_remove_lesson_pdf_remove_lesson_video_lesson_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='VIDEO'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.lesson')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.niveaux')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(blank=True, max_length=200)),
                ('reponse_vraie', models.BooleanField(max_length=1, verbose_name='la reponse vraie')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.question')),
            ],
        ),
    ]
