# Generated by Django 4.2.5 on 2023-09-29 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cours', '0010_lesson_video_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anwser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Identifiant de réponse')),
                ('texte_reponse', models.TextField(null=True, verbose_name='Texte de la réponse')),
                ('type_input', models.CharField(choices=[('radio', 'Radio'), ('checkbox', 'Checkbox'), ('text', 'Text')], default='radio', max_length=10, verbose_name="Type d'input")),
                ('est_correcte', models.BooleanField(default=False, verbose_name='Est correcte')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='question',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='auteur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Identifiant de question'),
        ),
        migrations.AddField(
            model_name='question',
            name='texte_question',
            field=models.TextField(null=True, verbose_name='Texte de la question'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cours.lesson'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='anwser',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='cours.question'),
        ),
    ]
